@base = http://localhost:8080/api

### 1. REGISTER
POST {{base}}/auth/register
Content-Type: application/json

{
  "firstName": "Ali",
  "lastName": "Huseynli",
  "email": "adminpass@gmail.com",
  "password": "Test123!"
}

### 2. LOGIN
POST {{base}}/auth/login
Content-Type: application/json

{
  "email": "ali@example.com",
  "password": "Test123!"
}


### 3. GET COURSES
GET {{base}}/courses/size/10/page/1

### 4. ENROLLMENTS
POST {{base}}/enrollments
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjEiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJhbGlAZXhhbXBsZS5jb20iLCJqdGkiOiJlMmEyYWRmYy0wMjE2LTRhMjMtYjBkZC0xMDZhZTVmZjM5YzYiLCJuYmYiOjE3Nzg2NzcxNjQsImV4cCI6MTc3ODY3ODk2NCwiaXNzIjoiaXNhZC1pZGVudGl0eSIsImF1ZCI6ImlzYWQtYXVkaWVuY2UifQ.XP_kN1-Cz5f0WuPkY1WW73Sa87deDTIAkfR4EOL0-lg
Content-Type: application/json

{
  "courseId": "11111111-1111-1111-1111-111111111111"
}

### 5. PAYMENTS
GET {{base}}/payments/history
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjEiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJhbGlAZXhhbXBsZS5jb20iLCJqdGkiOiJjODM1NGMxZS02NjVlLTQ4ZmMtODMzMy1lYjI2ZDQzMzk0NWQiLCJuYmYiOjE3Nzg2ODE3NTYsImV4cCI6MTc3ODY4MzU1NiwiaXNzIjoiaXNhZC1pZGVudGl0eSIsImF1ZCI6ImlzYWQtYXVkaWVuY2UifQ.kWCkZU4QdGcNQzaidy9OjH0KpuTQDmp_4-lV2-eFXAw
Content-Type: application/json
