// <auto-generated />
using System;
using EnrollmentService.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EnrollmentService.Persistence.Migrations
{
    [DbContext(typeof(EnrollmentServiceDbContext))]
    partial class EnrollmentServiceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EnrollmentService.Domain.Enrollment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EnrolledAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ProgressPercentage")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasDefaultValue(0m);

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Enrollments", "enrollments");
                });

            modelBuilder.Entity("EnrollmentService.Domain.LessonProgress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("EnrollmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("LessonId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("EnrollmentId", "LessonId")
                        .IsUnique()
                        .HasFilter("[EnrollmentId] IS NOT NULL");

                    b.ToTable("LessonProgresses", "enrollments");
                });

            modelBuilder.Entity("EnrollmentService.Domain.Snapshots.CourseSnapshot", b =>
                {
                    b.Property<string>("CourseId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("CourseId");

                    b.ToTable("CourseSnapshots", "enrollments");
                });

            modelBuilder.Entity("EnrollmentService.Domain.LessonProgress", b =>
                {
                    b.HasOne("EnrollmentService.Domain.Enrollment", null)
                        .WithMany("LessonProgresses")
                        .HasForeignKey("EnrollmentId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("EnrollmentService.Domain.Snapshots.CourseSnapshot", b =>
                {
                    b.OwnsMany("EnrollmentService.Domain.Snapshots.UnitSnapshot", "Units", b1 =>
                        {
                            b1.Property<Guid>("UnitId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("CourseId")
                                .IsRequired()
                                .HasColumnType("nvarchar(50)");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)");

                            b1.HasKey("UnitId");

                            b1.HasIndex("CourseId");

                            b1.ToTable("UnitSnapshots", "enrollments");

                            b1.WithOwner()
                                .HasForeignKey("CourseId");

                            b1.OwnsMany("EnrollmentService.Domain.Snapshots.LessonSnapshot", "Lessons", b2 =>
                                {
                                    b2.Property<Guid>("LessonId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<string>("Name")
                                        .IsRequired()
                                        .HasMaxLength(200)
                                        .HasColumnType("nvarchar(200)");

                                    b2.Property<Guid>("UnitId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.HasKey("LessonId");

                                    b2.HasIndex("UnitId");

                                    b2.ToTable("LessonSnapshots", "enrollments");

                                    b2.WithOwner()
                                        .HasForeignKey("UnitId");
                                });

                            b1.Navigation("Lessons");
                        });

                    b.Navigation("Units");
                });

            modelBuilder.Entity("EnrollmentService.Domain.Enrollment", b =>
                {
                    b.Navigation("LessonProgresses");
                });
#pragma warning restore 612, 618
        }
    }
}
